import Head from 'next/head'
import { Inter } from '@next/font/google'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillInstagram,AiFillLinkedin,AiFillGithub,} from "react-icons/ai"
import Img from "next/image";
import vec from "../public/vec.png";


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Muh Thoriq</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-slate-800 px-10">
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className="text-xl font-didot text-white">Thoriq</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill className="cursor-pointer text-2xl text-white"/></li>
              <li>
                <a className="bg-gradient-to-r from-slate-50 to-slate-300 text-black px-4 py-2 rounded-md ml-8" href="#">Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className="text-3xl text-white font-didot font-bold py-2">Muh Thoriq Akhdan</h2>
            <h3 className='text-2xl text-gray-300 py-2'>Student, Web developer and Software enthusiast</h3>
            <p className="text-md py-5 leading-3 text-gray-400">Currently student at Telkom university in Indonesia. Nice to meet you! </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-white'>
            <a href="https://www.instagram.com/thoriq.akhdn/">
              <AiFillInstagram />
            </a>
            <a href="https://github.com/thoriqakhdn">
              <AiFillGithub />
            </a>
            <a href="https://www.linkedin.com/in/thoriqakhdn/">
              <AiFillLinkedin />
            </a>

          </div>
          <div className='relative bg-gradient-to-b from-gray-500 rounded-full w-80 h-80 mt-20 mx-auto overflow-hidden'>
            <Img src={vec} layout="fill" objectFit='cover' alt={''} />
          </div>
        </section>
      </main>
    </>
  )
}
